### ISSUE TITLE
GetCompletionText returns only part of the full request after using CreateCompletionAsync 

### ISSUE THREAD

**Issue by guypld** [johniwasz/whetstone.chatgpt#16]
Hi,
I've tried the simple 'How is the weather' example, but strangely  I always get a few first words of the chat response, for example:
"The weather depends on your location. Generally it is advisable to check the"
What can be the reason for that?
thanks.

**Comment by johniwasz** [comment]
Processing the request and generating the response consume tokens. Tokens roughly correspond to the processing effort to understand words and parts of words in a prompt and the generation of words in completion response.

The default number of MaxTokens consumed is 16, but that can be adjusted.

When I send the following request I get:
"The weather depends on where you are. Please check the weather report for"

``` C#
using (IChatGPTClient client = ChatGPTTestUtilties.GetClient())
{
  var gptRequest = new ChatGPTCompletionRequest
  {
    Model = ChatGPTCompletionModels.Davinci,
    Prompt = "How is the weather?",
  };
  var response = await client.CreateCompletionAsync(gptRequest);
  string? completionText = response?.GetCompletionText();
  Console.WriteLine(completionText);
}       
```
The Usage property reports how many tokens were consumed processing and generating the completion request:

![image](https://user-images.githubusercontent.com/44126651/216774470-5f351b8e-5c8a-4047-9dfe-15cd5cdf3a92.png)

Increasing `MaxTokens` to 50 returns:

"The weather varies depending on the location and season. Please provide more information about your location for a better answer."

``` C#
  var gptRequest = new ChatGPTCompletionRequest
  {
    Model = ChatGPTCompletionModels.Davinci,
    Prompt = "How is the weather?",
    MaxTokens = 50,
  };
```
And it consumed a few more tokens than the original request:

![image](https://user-images.githubusercontent.com/44126651/216774662-fd339878-5c62-4712-9613-a38744e4834b.png)
