### ISSUE TITLE
Support gpt-3.5-turbo?

### ISSUE THREAD

**Issue by wt616** [johniwasz/whetstone.chatgpt#42]
Hi,could u support call the API from gpt-3.5-turbo?

**Comment by johniwasz** [comment]
Both GPT Turbo 3.5 and the Whisper API are being added.

Expect an update for Turbo support over the weekend.

**Comment by johniwasz** [comment]
Support for gpt-3.5-turbo, gpt-4, and whisper are now part of the 1.6.0 release:

https://www.nuget.org/packages/Whetstone.ChatGPT
